server:
  port: 8081

# This is a sample property to test if the config loads successfully
app:
  name: MyShop User Service
  env: Development

spring:
  datasource:
    # Changed port to 3307
    url: jdbc:mysql://192.168.221.136:3307/springcloud?characterEncoding=UTF8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
